/* Generated by Yosys 0.62+9 (git sha1 1717fa018, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module pwm_controller(clk, rst, duty_cycle, pwm_out);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [7:0] duty_cycle;
  wire [7:0] duty_cycle;
  output pwm_out;
  wire pwm_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire [7:0] _041_;
  wire [7:0] _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire [6:0] counter;
  INV_X1 _051_ (
    .A(counter[0]),
    .ZN(_009_)
  );
  INV_X1 _052_ (
    .A(counter[4]),
    .ZN(_010_)
  );
  INV_X1 _053_ (
    .A(counter[3]),
    .ZN(_011_)
  );
  INV_X1 _054_ (
    .A(counter[2]),
    .ZN(_012_)
  );
  INV_X1 _055_ (
    .A(counter[1]),
    .ZN(_013_)
  );
  INV_X1 _056_ (
    .A(counter[6]),
    .ZN(_014_)
  );
  INV_X1 _057_ (
    .A(_041_[7]),
    .ZN(_015_)
  );
  INV_X1 _058_ (
    .A(duty_cycle[5]),
    .ZN(_016_)
  );
  INV_X1 _059_ (
    .A(rst),
    .ZN(_017_)
  );
  NOR3_X1 _060_ (
    .A1(_009_),
    .A2(_012_),
    .A3(_013_),
    .ZN(_018_)
  );
  AND2_X1 _061_ (
    .A1(counter[3]),
    .A2(_018_),
    .ZN(_019_)
  );
  AND2_X1 _062_ (
    .A1(counter[4]),
    .A2(_019_),
    .ZN(_020_)
  );
  OAI21_X1 _063_ (
    .A(_017_),
    .B1(_020_),
    .B2(counter[5]),
    .ZN(_021_)
  );
  AOI21_X1 _064_ (
    .A(_021_),
    .B1(_020_),
    .B2(counter[5]),
    .ZN(_000_)
  );
  OAI21_X1 _065_ (
    .A(_017_),
    .B1(_019_),
    .B2(counter[4]),
    .ZN(_022_)
  );
  NOR2_X1 _066_ (
    .A1(_020_),
    .A2(_022_),
    .ZN(_001_)
  );
  OAI21_X1 _067_ (
    .A(_017_),
    .B1(_018_),
    .B2(counter[3]),
    .ZN(_023_)
  );
  NOR2_X1 _068_ (
    .A1(_019_),
    .A2(_023_),
    .ZN(_002_)
  );
  AOI21_X1 _069_ (
    .A(counter[2]),
    .B1(counter[1]),
    .B2(counter[0]),
    .ZN(_024_)
  );
  NOR3_X1 _070_ (
    .A1(rst),
    .A2(_018_),
    .A3(_024_),
    .ZN(_003_)
  );
  OAI21_X1 _071_ (
    .A(_017_),
    .B1(counter[1]),
    .B2(counter[0]),
    .ZN(_025_)
  );
  AOI21_X1 _072_ (
    .A(_025_),
    .B1(counter[1]),
    .B2(counter[0]),
    .ZN(_004_)
  );
  NAND2_X1 _073_ (
    .A1(_012_),
    .A2(duty_cycle[2]),
    .ZN(_026_)
  );
  AOI22_X1 _074_ (
    .A1(_013_),
    .A2(duty_cycle[1]),
    .B1(duty_cycle[0]),
    .B2(_009_),
    .ZN(_027_)
  );
  OAI22_X1 _075_ (
    .A1(_012_),
    .A2(duty_cycle[2]),
    .B1(duty_cycle[1]),
    .B2(_013_),
    .ZN(_028_)
  );
  OAI21_X1 _076_ (
    .A(_026_),
    .B1(_027_),
    .B2(_028_),
    .ZN(_029_)
  );
  OAI21_X1 _077_ (
    .A(_029_),
    .B1(duty_cycle[3]),
    .B2(_011_),
    .ZN(_030_)
  );
  AOI22_X1 _078_ (
    .A1(_010_),
    .A2(duty_cycle[4]),
    .B1(duty_cycle[3]),
    .B2(_011_),
    .ZN(_031_)
  );
  NOR2_X1 _079_ (
    .A1(_010_),
    .A2(duty_cycle[4]),
    .ZN(_032_)
  );
  AOI221_X1 _080_ (
    .A(_032_),
    .B1(_031_),
    .B2(_030_),
    .C1(counter[5]),
    .C2(_016_),
    .ZN(_033_)
  );
  NOR2_X1 _081_ (
    .A1(counter[5]),
    .A2(_016_),
    .ZN(_034_)
  );
  OAI22_X1 _082_ (
    .A1(_014_),
    .A2(duty_cycle[6]),
    .B1(_033_),
    .B2(_034_),
    .ZN(_035_)
  );
  AOI22_X1 _083_ (
    .A1(_015_),
    .A2(duty_cycle[7]),
    .B1(duty_cycle[6]),
    .B2(_014_),
    .ZN(_036_)
  );
  OAI21_X1 _084_ (
    .A(_017_),
    .B1(duty_cycle[7]),
    .B2(_015_),
    .ZN(_037_)
  );
  AOI21_X1 _085_ (
    .A(_037_),
    .B1(_036_),
    .B2(_035_),
    .ZN(_005_)
  );
  AND3_X1 _086_ (
    .A1(counter[5]),
    .A2(counter[6]),
    .A3(_020_),
    .ZN(_038_)
  );
  XNOR2_X1 _087_ (
    .A(_041_[7]),
    .B(_038_),
    .ZN(_039_)
  );
  NOR2_X1 _088_ (
    .A1(rst),
    .A2(_039_),
    .ZN(_006_)
  );
  AND2_X1 _089_ (
    .A1(_017_),
    .A2(_042_[0]),
    .ZN(_007_)
  );
  AOI21_X1 _090_ (
    .A(counter[6]),
    .B1(_020_),
    .B2(counter[5]),
    .ZN(_040_)
  );
  NOR3_X1 _091_ (
    .A1(rst),
    .A2(_038_),
    .A3(_040_),
    .ZN(_008_)
  );
  DFF_X1 _092_ (
    .CK(clk),
    .D(_007_),
    .Q(counter[0]),
    .QN(_042_[0])
  );
  DFF_X1 _093_ (
    .CK(clk),
    .D(_004_),
    .Q(counter[1]),
    .QN(_046_)
  );
  DFF_X1 _094_ (
    .CK(clk),
    .D(_003_),
    .Q(counter[2]),
    .QN(_047_)
  );
  DFF_X1 _095_ (
    .CK(clk),
    .D(_002_),
    .Q(counter[3]),
    .QN(_048_)
  );
  DFF_X1 _096_ (
    .CK(clk),
    .D(_001_),
    .Q(counter[4]),
    .QN(_049_)
  );
  DFF_X1 _097_ (
    .CK(clk),
    .D(_000_),
    .Q(counter[5]),
    .QN(_050_)
  );
  DFF_X1 _098_ (
    .CK(clk),
    .D(_008_),
    .Q(counter[6]),
    .QN(_043_)
  );
  DFF_X1 _099_ (
    .CK(clk),
    .D(_006_),
    .Q(_041_[7]),
    .QN(_044_)
  );
  DFF_X1 _100_ (
    .CK(clk),
    .D(_005_),
    .Q(pwm_out),
    .QN(_045_)
  );
  assign _042_[7:1] = { _041_[7], counter[6:1] };
  assign _041_[6:0] = counter;
endmodule
